/**
 * Type definitions for Proactive AI Alerts.
 */

/**
 * Alert priority levels determining display style and behavior.
 */
export type AlertPriority = 'critical' | 'warning' | 'info' | 'opportunity';

/**
 * Alert type categories.
 */
export type AlertType =
  | 'cash_crunch'
  | 'bill_collision'
  | 'invoice_risk'
  | 'opportunity'
  | 'anomaly';

/**
 * A single alert generated by the alert engine.
 */
export interface Alert {
  /** Unique identifier for this alert */
  id: string;
  /** Type of alert */
  type: AlertType;
  /** Priority level for styling and behavior */
  priority: AlertPriority;
  /** Short title for the alert */
  title: string;
  /** Detailed message (can be AI-generated) */
  message: string;
  /** Optional action link */
  actionUrl?: string;
  /** Optional action text */
  actionText?: string;
  /** Whether the alert can be dismissed */
  dismissible: boolean;
  /** Metadata for the alert (dates, amounts, etc.) */
  metadata?: Record<string, unknown>;
  /** Timestamp when alert was generated */
  createdAt: Date;
}

/**
 * Context data needed to generate alerts.
 */
export interface AlertContext {
  /** User's safety buffer amount */
  safetyBuffer: number;
  /** User's currency */
  currency: string;
  /** Calendar days with forecast data */
  calendarDays: CalendarDaySimple[];
  /** Monte Carlo risk metrics if available */
  riskMetrics?: RiskMetricsSimple;
  /** Outstanding invoices */
  invoices: InvoiceSimple[];
  /** Active bills */
  bills: BillSimple[];
  /** Active income sources */
  income: IncomeSimple[];
}

/**
 * Simplified calendar day for alert processing.
 */
export interface CalendarDaySimple {
  date: Date;
  balance: number;
  income: Array<{ name: string; amount: number; date: Date }>;
  bills: Array<{ name: string; amount: number; date: Date }>;
}

/**
 * Simplified risk metrics.
 */
export interface RiskMetricsSimple {
  probabilityBelowZero: number;
  probabilityBelowBuffer: number;
  expectedLowestBalance: number;
  worstCaseBalance: number;
  expectedDaysAtRisk: number;
}

/**
 * Simplified invoice data.
 */
export interface InvoiceSimple {
  id: string;
  clientName: string;
  amount: number;
  dueDate: string;
  status: string | null;
}

/**
 * Simplified bill data.
 */
export interface BillSimple {
  id: string;
  name: string;
  amount: number;
  frequency: string;
  dueDate: string | null;
}

/**
 * Simplified income data.
 */
export interface IncomeSimple {
  id: string;
  name: string;
  amount: number;
  frequency: string;
  nextDate: string | null;
}

/**
 * Result from an alert rule check.
 */
export interface AlertRuleResult {
  /** Whether the rule triggered an alert */
  triggered: boolean;
  /** The alert if triggered */
  alert?: Omit<Alert, 'id' | 'createdAt'>;
}

/**
 * Alert rule interface - each rule implements this.
 */
export interface AlertRule {
  /** Unique name for the rule */
  name: string;
  /** Check if the rule should trigger an alert */
  check(context: AlertContext): AlertRuleResult;
}
