/**
 * Default categorization rules for common merchants.
 * Rules are matched case-insensitively against transaction descriptions.
 * Higher priority rules are evaluated first.
 */

import type { CategorizationRule } from './types';

export const DEFAULT_CATEGORIZATION_RULES: CategorizationRule[] = [
  // ============================================
  // SUBSCRIPTIONS (Priority 100)
  // ============================================
  {
    id: 'sub-streaming-video',
    patterns: [
      'NETFLIX',
      'HULU',
      'DISNEY+',
      'DISNEY PLUS',
      'HBO MAX',
      'HBO',
      'PARAMOUNT+',
      'PARAMOUNT PLUS',
      'PEACOCK',
      'APPLE TV',
      'AMAZON PRIME VIDEO',
      'PRIME VIDEO',
      'YOUTUBE PREMIUM',
      'YOUTUBE TV',
      'CRUNCHYROLL',
      'FUBO',
      'SLING TV',
      'DISCOVERY+',
      'ESPN+',
    ],
    category: 'Subscriptions',
    priority: 100,
  },
  {
    id: 'sub-streaming-music',
    patterns: [
      'SPOTIFY',
      'APPLE MUSIC',
      'YOUTUBE MUSIC',
      'TIDAL',
      'PANDORA',
      'SOUNDCLOUD',
      'DEEZER',
      'AMAZON MUSIC',
      'AUDIBLE',
    ],
    category: 'Subscriptions',
    priority: 100,
  },
  {
    id: 'sub-software',
    patterns: [
      'ADOBE',
      'MICROSOFT 365',
      'OFFICE 365',
      'DROPBOX',
      'GOOGLE ONE',
      'GOOGLE STORAGE',
      'ICLOUD',
      'APPLE ONE',
      '1PASSWORD',
      'LASTPASS',
      'DASHLANE',
      'NOTION',
      'EVERNOTE',
      'SLACK',
      'ZOOM',
      'CANVA',
      'GRAMMARLY',
      'CHATGPT',
      'OPENAI',
      'GITHUB',
      'JETBRAINS',
      'FIGMA',
    ],
    category: 'Subscriptions',
    priority: 100,
  },
  {
    id: 'sub-gaming',
    patterns: [
      'XBOX GAME PASS',
      'XBOX LIVE',
      'PLAYSTATION PLUS',
      'PS PLUS',
      'NINTENDO ONLINE',
      'STEAM',
      'EPIC GAMES',
      'EA PLAY',
      'UBISOFT',
      'BLIZZARD',
      'TWITCH',
    ],
    category: 'Subscriptions',
    priority: 95,
  },
  {
    id: 'sub-news-media',
    patterns: [
      'NEW YORK TIMES',
      'NYT',
      'WALL STREET JOURNAL',
      'WSJ',
      'WASHINGTON POST',
      'THE ATLANTIC',
      'MEDIUM',
      'SUBSTACK',
      'PATREON',
    ],
    category: 'Subscriptions',
    priority: 90,
  },
  {
    id: 'sub-fitness',
    patterns: [
      'PELOTON',
      'STRAVA',
      'MYFITNESSPAL',
      'HEADSPACE',
      'CALM',
      'FITBIT PREMIUM',
      'APPLE FITNESS',
    ],
    category: 'Subscriptions',
    priority: 90,
  },

  // ============================================
  // UTILITIES (Priority 90-95)
  // ============================================
  {
    id: 'util-electric',
    patterns: [
      'ELECTRIC',
      'POWER COMPANY',
      'ENERGY',
      'PG&E',
      'PACIFIC GAS',
      'CON EDISON',
      'CONEDISON',
      'DUKE ENERGY',
      'SOUTHERN COMPANY',
      'DOMINION ENERGY',
      'ENTERGY',
      'XCEL ENERGY',
      'AEP',
      'NATIONAL GRID',
      'EVERSOURCE',
      'PPL ELECTRIC',
      'FIRSTENERGY',
      'AMEREN',
      'DTE ENERGY',
      'CONSUMERS ENERGY',
    ],
    category: 'Utilities',
    priority: 95,
  },
  {
    id: 'util-gas',
    patterns: [
      'GAS COMPANY',
      'NATURAL GAS',
      'ATMOS ENERGY',
      'NICOR GAS',
      'PEOPLES GAS',
      'SOUTHWEST GAS',
      'SPIRE',
      'CENTERPOINT',
    ],
    category: 'Utilities',
    priority: 95,
  },
  {
    id: 'util-water',
    patterns: [
      'WATER UTILITY',
      'WATER DEPT',
      'WATER DISTRICT',
      'WATER BILL',
      'SEWER',
      'AMERICAN WATER',
      'AQUA AMERICA',
    ],
    category: 'Utilities',
    priority: 95,
  },
  {
    id: 'util-internet-cable',
    patterns: [
      'COMCAST',
      'XFINITY',
      'SPECTRUM',
      'CHARTER',
      'AT&T INTERNET',
      'ATT INTERNET',
      'VERIZON FIOS',
      'FIOS',
      'COX COMMUNICATION',
      'FRONTIER COMM',
      'CENTURYLINK',
      'LUMEN',
      'OPTIMUM',
      'ALTICE',
      'MEDIACOM',
      'WINDSTREAM',
      'GOOGLE FIBER',
      'STARLINK',
    ],
    category: 'Utilities',
    priority: 90,
  },
  {
    id: 'util-phone',
    patterns: [
      'T-MOBILE',
      'TMOBILE',
      'VERIZON WIRELESS',
      'VZW',
      'AT&T WIRELESS',
      'ATT WIRELESS',
      'AT&T MOBILITY',
      'SPRINT',
      'MINT MOBILE',
      'VISIBLE',
      'CRICKET',
      'BOOST MOBILE',
      'METRO BY T-MOBILE',
      'US CELLULAR',
      'GOOGLE FI',
    ],
    category: 'Utilities',
    priority: 90,
  },
  {
    id: 'util-trash',
    patterns: [
      'WASTE MANAGEMENT',
      'REPUBLIC SERVICES',
      'TRASH',
      'GARBAGE',
      'RECYCLING',
      'SANITATION',
    ],
    category: 'Utilities',
    priority: 85,
  },

  // ============================================
  // INSURANCE (Priority 95)
  // ============================================
  {
    id: 'ins-auto',
    patterns: [
      'GEICO',
      'STATE FARM',
      'PROGRESSIVE',
      'ALLSTATE',
      'LIBERTY MUTUAL',
      'USAA',
      'FARMERS INS',
      'NATIONWIDE',
      'TRAVELERS',
      'AMERICAN FAMILY',
      'ERIE INSURANCE',
      'AUTO-OWNERS',
      'SAFECO',
      'MERCURY INS',
      'ESURANCE',
      'ROOT INS',
      'LEMONADE',
    ],
    category: 'Insurance',
    priority: 95,
  },
  {
    id: 'ins-health',
    patterns: [
      'BLUE CROSS',
      'BCBS',
      'AETNA',
      'CIGNA',
      'UNITED HEALTH',
      'UNITEDHEALTHCARE',
      'UHC',
      'KAISER',
      'HUMANA',
      'ANTHEM',
      'CENTENE',
      'MOLINA',
      'OSCAR HEALTH',
    ],
    category: 'Insurance',
    priority: 95,
  },
  {
    id: 'ins-life-home',
    patterns: [
      'LIFE INSURANCE',
      'METLIFE',
      'PRUDENTIAL',
      'NORTHWESTERN MUTUAL',
      'NEW YORK LIFE',
      'LINCOLN FINANCIAL',
      'PRINCIPAL',
      'HOMEOWNERS INS',
      'RENTERS INS',
    ],
    category: 'Insurance',
    priority: 90,
  },
  {
    id: 'ins-generic',
    patterns: ['INSURANCE PREMIUM', 'INS PREMIUM'],
    category: 'Insurance',
    priority: 70,
  },

  // ============================================
  // RENT/MORTGAGE (Priority 95)
  // ============================================
  {
    id: 'rent-mortgage-lenders',
    patterns: [
      'MORTGAGE',
      'HOME LOAN',
      'WELLS FARGO MTG',
      'WELLS FARGO MORTGAGE',
      'CHASE MTG',
      'CHASE MORTGAGE',
      'QUICKEN LOANS',
      'ROCKET MORTGAGE',
      'FREEDOM MORTGAGE',
      'PENNYMAC',
      'LOANCARE',
      'MR COOPER',
      'NATIONSTAR',
      'CALIBER HOME',
      'US BANK MORTGAGE',
      'BANK OF AMERICA MTG',
      'BOA MORTGAGE',
      'CITIMORTGAGE',
      'PHH MORTGAGE',
      'SPECIALIZED LOAN',
    ],
    category: 'Rent/Mortgage',
    priority: 95,
  },
  {
    id: 'rent-property-mgmt',
    patterns: [
      'RENT PAYMENT',
      'APARTMENT RENT',
      'PROPERTY MGMT',
      'PROPERTY MANAGEMENT',
      'GREYSTAR',
      'EQUITY RESIDENTIAL',
      'AVALON',
      'CAMDEN',
      'MAA',
      'UDR',
      'ESSEX',
      'INVITATION HOMES',
      'AMERICAN HOMES',
      'PROGRESS RESIDENTIAL',
      'ZUMPER',
      'APARTMENTS.COM',
      'COZY',
      'ZILLOW RENT',
    ],
    category: 'Rent/Mortgage',
    priority: 95,
  },
  {
    id: 'rent-hoa',
    patterns: ['HOA', 'HOMEOWNERS ASSOC', 'CONDO ASSOC', 'CONDO FEE'],
    category: 'Rent/Mortgage',
    priority: 85,
  },

  // ============================================
  // TRANSPORTATION (Priority 80)
  // If user doesn't have Transportation category, these won't match
  // and will fall through to AI categorization
  // ============================================
  {
    id: 'transport-gas-stations',
    patterns: [
      'SHELL',
      'EXXON',
      'MOBIL',
      'CHEVRON',
      'TEXACO',
      'BP ',
      'ARCO',
      'VALERO',
      'MARATHON',
      'SUNOCO',
      'CITGO',
      'PHILLIPS 66',
      'CONOCO',
      '76 GAS',
      'SPEEDWAY',
      'KWIK TRIP',
      'WAWA',
      'SHEETZ',
      'RACETRAC',
      'QUIKTRIP',
      'LOVES TRAVEL',
      'PILOT TRAVEL',
      'FLYING J',
      'TA TRAVEL',
      'CASEY',
      'COSTCO GAS',
      'SAMS CLUB FUEL',
      'BUCCEES',
    ],
    category: 'Transportation',
    priority: 80,
  },
  {
    id: 'transport-rideshare',
    patterns: ['UBER', 'LYFT', 'GRAB', 'DIDI'],
    category: 'Transportation',
    priority: 80,
  },
  {
    id: 'transport-parking-tolls',
    patterns: [
      'PARKING',
      'PARK METER',
      'SPOTHERO',
      'PARKWHIZ',
      'TOLL',
      'EZPASS',
      'E-ZPASS',
      'SUNPASS',
      'FASTRAK',
      'TXTAG',
      'PIKEPASS',
    ],
    category: 'Transportation',
    priority: 75,
  },
  {
    id: 'transport-public',
    patterns: [
      'METRO',
      'SUBWAY',
      'MTA',
      'WMATA',
      'BART',
      'MARTA',
      'SEPTA',
      'MBTA',
      'CTA',
      'TRANSIT',
      'BUS PASS',
    ],
    category: 'Transportation',
    priority: 75,
  },

  // ============================================
  // FOOD & DINING
  // ============================================
  {
    id: 'food-delivery',
    patterns: [
      'DOORDASH',
      'UBER EATS',
      'UBEREATS',
      'GRUBHUB',
      'POSTMATES',
      'SEAMLESS',
      'INSTACART',
      'SHIPT',
    ],
    category: 'Food & Dining',
    priority: 70,
  },

  // ============================================
  // SHOPPING
  // ============================================
  {
    id: 'shop-amazon',
    patterns: ['AMAZON', 'AMZN', 'PRIME'],
    category: 'Shopping',
    priority: 60,
  },
];

/**
 * Merge user-defined rules with defaults.
 * User rules take priority over defaults.
 */
export function mergeWithUserRules(
  userRules: CategorizationRule[] = []
): CategorizationRule[] {
  return [...userRules, ...DEFAULT_CATEGORIZATION_RULES].sort(
    (a, b) => b.priority - a.priority
  );
}
